### ISSUE TITLE
wat?

### ISSUE THREAD

**Issue by koriroys** [walsh9/dragon-taxes#16]
<ul id="final-report">
  <li><b>Line A1:</b> No problems here!</li>
  <li><b>Line A2:</b> You overreported by 2,520 G.</li>
  <li><b>Line A3:</b> No problems here!</li>
  <li><b>Line A4:</b> No problems here!</li>
  <li><b>Line A5:</b> No problems here!</li>
  <li><b>Line A6:</b> This line was too high by 2,520 G.</li>
  <li><b>Line B1:</b> No problems here!</li>
  <li><b>Line B2:</b> No problems here!</li>
  <li><b>Line B3:</b> This line was too low by 8,412 G.</li>
  <li><b>Line B4:</b> No problems here!</li>
  <li><b>Line B5:</b> No problems here!</li>
  <li><b>Line B6:</b> No problems here!</li>
  <li><b>Line B7:</b> This line was too low by 7,235 G.</li>
  <li><b>Line C1:</b> This line was too low by 292,774 G.</li>
  <li><b>Line C2:</b> You underpaid by 29,277 G. Expect a visit from the auditor!</li>
  <li><b>You asked for extra time? That goes on your permanent record!</b></li>
</ul>

**Comment by walsh9** [comment]
Hello! Thanks for the issue report.

Is this from the Post-Jam version or the LD33 version?

Also, what exactly are you reporting...?  Is this a comment about the general user-friendliness of the final score breakdown (which could use some work). Or is this about something specific with the numbers?  There was a bug with reporting for lines B6 and B7 in the LD33 version but it should have been fixed in the Post-Jam version...

Thanks!

**Comment by koriroys** [comment]
I'm not sure what version it was. I was followed the link from lobste.rs. :)

Mostly I was just confused as to how line C1 could be too low by a few hundred thousand, when line B7 and A6 were off by a few thousand.

**Comment by walsh9** [comment]
The link there looks like the latest version.

It could be a problem with the game but it could also be something as simple as a typo or two somewhere in the final sum up. Scoring was added around the last minute so it's sort of bare bones. Without all the numbers and the game state it's really hard for me to tell what happens and it takes quite a while to run test games manually.   

I think what I really need to do is add a fully-itemized report of how it 'should' be done along with allowing access all the paperwork again after the end screen so the player can compare final results for themselves.  That should also make any specific scoring bugs easier to spot and report. Maybe I'll work on that this weekend.

I'm gonna open a new issue for a fully itemized report and close this one.

Thanks again for the report.

**Comment by walsh9** [comment]
Proposed solution in issue #17

**Comment by koriroys** [comment]
Thanks for the game. :)
